version: "3"

services:
  db:
    container_name: postgres
    image: postgres:14.9
    volumes:
      - burger_db:/var/lib/postgresql/14/main
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    restart: always

  frontend:
    build: ../Frontend
    container_name: nodejs
    command: ./node_modules/.bin/parcel build bundles-src/index.js --dist-dir bundles --public-url="./"
    volumes:
      - bundles_volume:/Frontend/bundles/.

  backend:
    build: ../Backend
    container_name: django
    command: gunicorn -b 0.0.0.0:8000 star_burger.wsgi:application
    ports:
      - "8000:8000"
    volumes:
      - bundles_volume:/Backend/bundles
      - ../Backend/media:/Backend/media
      - static_volume:/Backend/static
    env_file:
      - ./.env
    depends_on:
      - db

volumes:
  burger_db:
  static_volume:
  bundles_volume: